version: "3.3"

services:
  mosquitto:
    container_name: mosquitto-srv
    image: eclipse-mosquitto:latest
    user: "0:0"
    restart: always
    ports:
      - "1883:1883"
    networks:
      - iot
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.log:/etc/mosquitto/mosquitto.log
      - ./mosquitto/certs/:/etc/mosquitto/certs/
      - ./mosquitto/data:/mosquitto/data

  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - ./grafana/fullchain.pem:/etc/grafana/fullchain.pem
      - ./grafana/privkey.pem:/etc/grafana/privkey.pem
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dados:/var/lib/grafana

  postgresrv:
    container_name: postgres-srv
    image: postgres
    environment:
      - POSTGRES_DB=MQTTbee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - iot

## sistemas Python
  mqtt2psql:
    image: python-psql-mqtt
    restart: always
    volumes: 
      - ./scripts/mqtt2psql:/app
    depends_on:
      - postgresrv
      - mosquitto
    networks:
      - iot
        #    RUN pip install --upgrade pip && pip3 install paho-mqtt && pip3 install psycopg2    
  
  painel:
    build: scripts/painel/
    restart: always
    volumes:
      - ./scripts/painel/:/app
      - ./scripts/config.py:/app/config.py
    networks:
      - iot
    depends_on:
      - postgresrv
      - mosquitto

# sincroniza o BD local com a Nuvem
  sincnuvem:
    build: scripts/sincNuvem
    restart: always
    volumes:
      - ./scripts/sincNuvem:/app
      - ./scripts/config.py:/app/config.py
    depends_on:
      - postgresrv
      - mosquitto

    networks:
      - iot

  
  ntp: 
    image: cturra/ntp:latest 
    container_name: ntp 
    restart: always 
    ports: 
      - 123:123/udp 
    environment:  
      - NTP_SERVERS=time.cloudflare.com 
      - LOG_LEVEL=0

networks:
  iot:
    driver: bridge

