version: "3.3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "8884:8884"
      - "9001:9001"
    networks:
      - iot
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.log:/etc/mosquitto/mosquitto.log
      - ./mosquitto/certs/:/etc/mosquitto/certs/

  
  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot
    volumes:
      - /root/projetoDados/influxdb/:/var/lib/influxdb/
  
  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - ./grafana/fullchain.pem:/etc/grafana/fullchain.pem
      - ./grafana/privkey.pem:/etc/grafana/privkey.pem
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dados:/var/lib/grafana
    depends_on:
      - influxdb

networks:
  iot:

